### ISSUE TITLE
Multiple Configuration

### ISSUE THREAD

**Issue by mayureshs** [therealjordanlee/AzureFunctionDependencyInjection#1]
Thanks for the example. I was not able to find the explanation on MS docs. Question: If there are multiple Configuration to be bound then would this statement be repeated as many times ?

        builder
                .Services
                .AddOptions<NewConfig1Configuration>()
                .Configure<IConfiguration>((newConfig1Settings, configuration) =>
                {
                    configuration
                        .GetSection("Config1")
                        .Bind(newConfig1Settings);
                });

    builder
                .Services
                .AddOptions<NewConfig2Configuration>()
                .Configure<IConfiguration>((newConfig2Settings, configuration) =>
                {
                    configuration
                        .GetSection("Config2")
                        .Bind(newConfig2Settings);
                });

**Comment by therealjordanlee** [comment]
Hi @mayureshs, apologies for not getting back to you on this (I haven't been paying attention to my older works).
You're exactly right - if you have multiple configurations, just repeat the statement. But its probably more efficient to write a method for this:

```
private void AddConfiguration<TOptions>(IFunctionsHostBuilder builder, string section) where TOptions : class
        {
            builder.Services
                .AddOptions<TOptions>()
                .Configure<IConfiguration>((settings, configuration) =>
                {
                    configuration.GetSection(section).Bind(settings);
                });
        }
```

And then you'd can add multiple options like this:
```
AddConfiguration<MessageResponderConfiguration>(builder, "MessageResponder");
AddConfiguration<RandomResponderConfiguration>(builder, "RandomResponder");
```

I've pushed a branch which implements this if you want to see the full code:
https://github.com/therealjordanlee/AzureFunctionDependencyInjection/tree/multiple-configurations

Cheers!

**Comment by mayureshs** [comment]
Thanks for the update !!
